import actionService from '#server/services/action/actionService';

const ERRORS = {
    undefined: { code: 500, message: 'Une erreur inconnue est survenue' },
};

export default async (req, res, next) => {
    try {
        const actions = await actionService.fetch(
            req.user.permissions.action.read,
            req.user.permissions.action_finances.access || { allowed: false },
            [req.params.id],
        );

        if (actions.length === 0) {
            return res.status(404).send({});
        }

        return res.status(200).send(actions[0]);
    } catch (error) {
        const { code, message } = ERRORS[error?.code] || ERRORS.undefined;
        res.status(code).send({
            user_message: message,
        });

        return next(error?.nativeError || error);
    }
};
